# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildApp
    jobs:
      - job: BuildFrontend
        displayName: BuildFrontendApp
        steps:
          - script: echo "Build frontend App"
      - job: BuildBackend
        displayName: BuildBackendApp
        steps:
          - script: "echo build backend APP"
  
  - stage: DeploytoDev
    jobs:
      - job: DeployFrontend
        displayName: DeployFrontendApp
        steps:
          - script: echo "Deploy frontend app to ${{ parameters.environment}}"
      - job: DeployBackend
        displayName: DeployBackendApp
        steps:
          - script: echo "Deploy backend app to ${{ parameters.environment}}"
  
  - stage: DeploytoProd
    jobs:
      - job: DeployFrontendToProd
        displayName: DeploytoProdenv
        steps:
          - script: echo "Deploy frontend app to ${{ parameters.environment}} environment"
      - job: DeployBackendToProd
        displayName: BackendToProdenv
        steps:
          - script: echo "Deploy backend to ${{ parameters.environment}} environment"
