# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TestApp
    jobs:
      - job: TestFrontend
        displayName: TestFrontendApp
        steps:
          - script: echo "Test the appplication"

  
  - stage: DeployUS1
    dependsOn: TestApp
    jobs:
      - job: DeployUS1
        displayName: DeployApptoUS1
        steps:
          - script: echo "Deploy application US1 to ${{ parameters.environment}}"
  
  - stage: DeployUS2
    dependsOn: TestApp
    jobs:
      - job: DeployUS2
        displayName: DeployApptoUS2
        steps:
          - script: echo "Deploy application US2 to ${{ parameters.environment}} environment"
  
  - stage: DeployEurope
    dependsOn:
    - DeployUS1
    - DeployUS2
    jobs:
      - job: DeploytoEurope
        displayName: DeployApptoEurope
        steps:
          - script: echo "Deploy application to Europe in ${{ parameters.environment}} environment"
 