# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: New variable group nithish
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "step: 1 print date"
    date
    echo "show current directory"
    pwd
  displayName: 'Run a multi-line script'

- script: echo "Deploying to $(APP_NAME) to $(APP_ENV) evvironment"
  displayName: 'using variables'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'helloworld'
    publishLocation: 'pipeline'
