# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prod

pool:
  vmImage: ubuntu-latest

jobs:
  - job: job1
    steps:
      - script: echo "This is job1 deploying to ${{ parameters.environment}}"
        displayName: 'Job1 is executed'
