# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildStage
    displayName: Build
    jobs:
      - job: BuildApp
        displayName: buildaapplication
        steps:
          - script: echo "hi this is my build application" > output.txt
          - publish: $(System.DefaultWorkingDirectory)/output.txt
            artifact: drop

  - stage: Deploystage
    displayName: Deploy
    jobs:
      - deployment: DeployApp
        displayName: DeployTheApplication
        environment: prod
        strategy:
         runOnce:
           deploy:
             steps:
               - download: current
                 artifact: drop
               - script: echo "Starting deployment to IIS server"

               
               - task: PowerShell@2
                 displayName: "Deploy To Web Server 1"
                 inputs:
                   targetType: inline
                   script: echo " deployded webserver 1"
              
               - task: PowerShell@2
                 displayName: "Deploy webserver 2"
                 inputs:
                   targetType: inline
                   script: echo "Deployded Webserver 2"
               - script: echo "Deployment completed"
